In [1]:
import yfinance as yf
from datetime import datetime
import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.tsa.stattools import coint
import statsmodels.api as sm
import pandas as pd
import numpy as np

In [2]:
START = datetime(2000, 1, 1)
END = datetime(2021, 1, 8)
temp = yf.Ticker("TQQQ")
hist_temp = temp.history(start=START, end=END)

In [3]:
hist_temp

              Open    High     Low   Close    Volume  Dividends  Stock Splits
Date
2010-02-11    1.62    1.74    1.62    1.73    864000        0.0           0.0
2010-02-12    1.68    1.75    1.67    1.73   2150400        0.0           0.0
2010-02-16    1.77    1.80    1.75    1.80   2404800        0.0           0.0
2010-02-17    1.82    1.83    1.80    1.83   4795200        0.0           0.0
2010-02-18    1.83    1.88    1.82    1.87   9715200        0.0           0.0
...            ...     ...     ...     ...       ...        ...           ...
2020-12-31  180.27  182.48  178.33  181.80  13330900        0.0           0.0
2021-01-04  184.08  184.39  166.83  173.85  24684000        0.0           0.0
2021-01-05  172.28  178.56  172.28  178.21  14839100        0.0           0.0
2021-01-06  169.90  178.34  168.22  170.84  26341300        0.0           0.0
2021-01-07  175.37  184.65  175.35  183.18  15461900        0.0           0.0

[2746 rows x 7 columns]